version: '3'
networks:
      backend:
        driver: bridge
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB2019!
    ports:
      - "27017:27017"
    volumes:
      - c:\dados\volumes\mongo:/var/opt/mssql/data
    networks:
      - backend
  api:
    build:
        context: .
        dockerfile: Dockerfile
    networks: 
      - backend
    ports:
      - "80:80"
      - "44359:44359"
    environment:
        MongoSettings__Connection: mongodb://root:MongoDB2019!@mongo:27017
        MongoSettings__DatabaseName: CasaDoCodigo
        ASPNETCORE_ENVIRONMENT: Development
